routes/web.php
    return view('auth.login');
})->name("login");


Route::post('/login','AuthController@login')->name('process_login');
Route::get('/logout','AuthController@logout')->name('logout');




Route::group(array('middleware' => 'auth'), function(){

    Route::get('/dashboard','DashboardController@index');
    Route::get('/','DashboardController@index')->name('dashboard');


    Route::group(['middleware' => ['role:Admin|Super-Admin']], function () {

        Route::get('/departments','DepartmentController@index')->name('departments');
        Route::get('/add_department','DepartmentController@add')->name('add_department');
        Route::post('/add_department','DepartmentController@store')->name('add_department');
        Route::get('/delete_department/{id}','DepartmentController@delete')->name('delete_department');
        Route::get('/restore_department/{id}','DepartmentController@restore')->name('restore_department');
        Route::get('/edit_department/{id}','DepartmentController@edit')->name('edit_department');
        Route::post('/edit_department/{id}','DepartmentController@save_edit')->name('edit_department');

        Route::get('/regions','RegionController@index')->name('regions');
        Route::get('/add_region','RegionController@add')->name('add_region');
        Route::post('/add_region','RegionController@store')->name('add_region');
        Route::get('/delete_region/{id}','RegionController@delete')->name('delete_region');
        Route::get('/restore_region/{id}','RegionController@restore')->name('restore_region');
        Route::get('/edit_region/{id}','RegionController@edit')->name('edit_region');
        Route::post('/edit_region/{id}','RegionController@save_edit')->name('edit_region');
        

    
    
        Route::get('/users','UserController@index')->name('users');
        Route::get('/add_user','UserController@add')->name('add_user');
        Route::post('/add_user','UserController@store')->name('add_user');
        Route::get('/delete_user/{id}','UserController@delete')->name('delete_user');
        Route::get('/restore_user/{id}','UserController@restore')->name('restore_user');
        Route::get('/edit_user/{id}','UserController@edit')->name('edit_user');
        Route::post('/edit_user/{id}','UserController@save_edit')->name('edit_user');
    
    
        Route::get('/contribution_types','ContributionTypeController@index')->name('contribution_types');
        Route::get('/add_contribution_type','ContributionTypeController@add')->name('add_contribution_type');
        Route::post('/add_contribution_type','ContributionTypeController@store')->name('add_contribution_type');
        Route::get('/delete_contribution_type/{id}','ContributionTypeController@delete')->name('delete_contribution_type');
        Route::get('/restore_contribution_type/{id}','ContributionTypeController@restore')->name('restore_contribution_type');
        Route::get('/edit_contribution_type/{id}','ContributionTypeController@edit')->name('edit_contribution_type');
        Route::post('/edit_contribution_type/{id}','ContributionTypeController@save_edit')->name('edit_contribution_type');
        
        Route::get('/make_contribution',function () {
            return view('pages.initiate_contribution');
        })->name('make_contribution');
        Route::get('/single_contribution','ContributionController@single_contribution')->name('single_contribution');
        Route::post('/single_contribution','ContributionController@process_single_contribution')->name('single_contribution');
    
    
        Route::get('/department_contribution','ContributionController@department_contribution')->name('department_contribution');
        Route::post('/department_contribution','ContributionController@process_department_contribution')->name('department_contribution');
    
    
        Route::get('/contributions','ContributionController@index')->name('contributions');
        Route::get('/contribution/{id}','ContributionController@edit')->name('edit_contribution');
        Route::post('/contribution','ContributionController@update')->name('update_contribution');
        
        Route::get('/withdrawals','WithdrawalController@index')->name('withdrawals');
        Route::get('/disapprove_withdrawal/{id}','WithdrawalController@delete')->name('disapprove_withdrawal');
        Route::get('/approve_withdrawal/{id}','WithdrawalController@approve')->name('approve_withdrawal');
        
        
        
        Route::get('/report',function () {
            return view('pages.initiate_report');
        })->name('report');
    

        Route::get('/withdraw_report','ReportController@withdraw_report')->name('withdraw_report');
        Route::get('/contribution_report','ReportController@contribution_report')->name('contribution_report');
        Route::get('/employee_contribution_report','ReportController@employee_contribution_report')->name('employee_contribution_report');
        Route::post('/employee_contribution_report','ReportController@employee_contribution_report_process')->name('employee_contribution_report');

        

        //Importing Data
        Route::post('/process_user_import','ImportController@user_import')->name('process_user_import');
        Route::post('/process_contribution_import','ImportController@contribution_import')->name('process_contribution_import');
        
        Route::get('/import',function () {
            return view('pages.initiate_import');
        })->name('import');

        Route::get('/contribution_import',function () {
            return view('pages.contribution_import');
        })->name('contribution_import');

        Route::get('/user_import',function () {
            return view('pages.user_import');
        })->name('user_import');
          

        //GENERATING EXCEL EXPORT
        Route::post('/export_excel_withdrawals','ExportController@withdrawal_export')->name('export_excel_withdrawal');
        Route::post('/export_excel_contributions','ExportController@contribution_export')->name('export_excel_contribution');
        Route::get('/export_excel_employee_contributions/{id}','ExportController@employee_contribution_export_all')->name('export_excel_employee_contributions');

        //GENERATING PDF EXPORT
         Route::post('/export_pdf_withdrawals','ExportController@withdrawal_export_pdf')->name('export_pdf_withdrawal');
         Route::post('/export_pdf_contributions','ExportController@contribution_export_pdf')->name('export_pdf_contribution');
         Route::get('/export_pdf_employee_contributions/{id}','ExportController@employee_contribution_export_all_pdf')->name('export_pdf_employee_contributions');

         
         Route::get('/export_all_withdrawals_to_pdf','ExportController@export_all_withdrawals_pdf')->name('export_all_withdrawals_to_pdf');
         Route::get('/export_all_contributions_to_pdf','ExportController@export_all_contributions_pdf')->name('export_all_contributions_to_pdf');

         Route::get('/export_all_withdrawals_to_excel','ExportController@export_all_withdrawals_excel')->name('export_all_withdrawals_to_excel');
         Route::get('/export_all_contributions_to_excel','ExportController@export_all_contributions_excel')->name('export_all_contributions_to_excel');
        

         //Export Viewers
         Route::get('/exports',function () {
            return view('pages.initiate_exports_viewer');
        })->name('exports');

        Route::get('/exports_contributions',"DownloadController@contributions_listing")->name('contributions_exports');
        Route::get('/exports_withdrawals',"DownloadController@withdrawals_listing")->name('withdrawals_exports');

        //Download Exports
        Route::get('/download_contributions_exports',"DownloadController@download_contributions_pdf")->name('download_contributions_exports');
        Route::get('/download_withdrawals_exports',"DownloadController@download_withdrawals_pdf")->name('download_withdrawals_exports');
        


    });
    
    
    Route::get('/my_contributions','ContributionController@my_contributions')->name('my_contributions');
    Route::get('/my_withdrawals','WithdrawalController@my_withdrawals')->name('my_withdrawals');

    //EXPORTING REPORT
    Route::post('/my_contribution_excel_export','ExportController@my_contribution_export')->name('my_contribution_excel_export');
    Route::post('/my_contribution_pdf_export','ExportController@my_contribution_pdf_export')->name('my_contribution_pdf_export');
    
    Route::post('/my_withdrawal_excel_export','ExportController@my_withdrawal_export')->name('my_withdrawal_excel_export');
    Route::post('/my_withdrawal_pdf_export','ExportController@my_withdrawal_pdf_export')->name('my_withdrawal_pdf_export');
    


    Route::get('/make_withdrawal',function () {
        return view('pages.make_withdrawal');
    })->name('make_withdrawal');
    Route::post('/make_withdrawal','WithdrawalController@make_withdrawal')->name('make_withdrawal');

    Route::get('/profile','UserController@profile')->name('profile');

    Route::get('/edit_profile',function () {
        $user = Auth::user();
        return view('pages.edit_profile')->with(["user"=>$user]);
    })->name('edit_profile');
    
    Route::post('/update_profile','UserController@update_profile')->name('update_profile');

    Route::get('/change_password',function () {
        return view('pages.change_password');
    })->name('change_password');

    Route::post('/change_password','UserController@change_password')->name('change_password');
    
    
    //Route::get('/report','ReportController@index')->name('report');
    
    //RollOver Functions
    Route::get('/rollover','RollOverController@index')->name('roll_over');
    Route::post('/rollover','RollOverController@store')->name('process_roll_over');

    //Interest Functions
    Route::get('/interest','InterestController@index')->name('interest');
    Route::post('/interest','InterestController@store')->name('process_interest');
    

app/Contribution.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Contribution extends Model
{
    //
    use SoftDeletes;

    protected $fillable = [
        'user_id', 'amount', 'approver_id', 'contribution_type_id','remark',
    ];


    public function getFormattedDateAttribute()
    {
        $startDate = strtoupper(date("F Y", strtotime($this->created_at)));
        return "{$startDate}";
    }

    public function getFormattedAmountAttribute()
    {
        $amount = number_format( $this->amount, 2 );
        return "{$amount}";
    }

    public function creditor()
    {
        return $this->hasOne('App\User', 'id','approver_id');
    }

    public function contribution_type()
    {
        return $this->hasOne('App\ContributionType', 'id','contribution_type_id');
    }

    public function user()
    {
        return $this->hasOne('App\User', 'id','user_id');
    }

}

app/RollOver.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use \Carbon;


class RollOver extends Model
{
    //

    public function getFormattedStartDateAttribute()
    {
        $startDate = strtoupper(date("M Y", strtotime($this->start_date)));
        return "{$startDate}";
    }

    public function getFormattedEndDateAttribute()
    {
        $startDate = strtoupper(date("M Y", strtotime($this->end_date)));
        return "{$startDate}";
    }

    public function getReadableEndDateAttribute()
    {
        $startDate = strtoupper(date("M Y", strtotime($this->end_date)));
        return "{$startDate}";
    }

    public function getFormattedBalanceAttribute()
    {
        $balance = number_format( $this->balance, 2 );
        return "{$balance}";
    }

    public function getFormattedWithdrawnAttribute()
    {
        $amount_withdrawn = number_format( $this->amount_withdrawn, 2 );
        return "{$amount_withdrawn}";
    }

    public function getFormattedOldBalanceAttribute()
    {
        $balance = number_format( ( $this->balance - $this->amount_withdrawn ) , 2 );
        return "{$balance}";
    }


    public function approver()
    {
        return $this->hasOne('App\User','id', 'approver_id');
    }



}

resources/views/pdf/contributions.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
    
    <style>

            .p2{
                padding: 5px;
            }
    
            table {
                border-collapse: collapse;
            }
    
            table, th, td {
                border: 1px solid black;
            }
    
            table {
                width: 100%;
            }
    
            th {
                height: 20px;
            }
    
        </style>

</head>
<body>

    <p style="text-align:center;padding:10px;"><h3> Contributions Report </h3></p>
<table>
        <thead>
            <tr>
                <th class="p2" >ID</th>
                <th class="p2" >Fullname</th>
                <th class="p2" >Amount</th>
                <th class="p2" >Contribution Type</th>
                <th class="p2" >Remark</th>
                <th class="p2" >Credited By</th>
                <th class="p2" >Credited On</th>
            </tr>
        </thead>

        <tbody>

            @foreach ($contributions as $contribution)

                
                    <tr>
                        <td class="p2" >{{ $loop->iteration }}</td>
                        <td class="p2" >{{ $contribution->user->fullname }} </td>
                        <td class="p2" >{{ $contribution->amount }} </td>
                        <td class="p2" >{{ $contribution->contribution_type->name }} </td>
                        <td class="p2" >{{ $contribution->remark }} </td>
                        <td class="p2" >{{ $contribution->creditor->fullname }} </td>
                        <td class="p2" >{{ $contribution->created_at }}</td>
                    </tr>

            @endforeach
            
        </tbody>
</table>

</body>
</html>

resources/views/pdf/employee_contributions.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>

    <p style="text-align:center;padding:10px;"><h3> Employee Contributions </h3></p>
<table border="1">
        <thead>
            <tr>
            <th>ID</th>
            <th>Fullname</th>
            <th>Amount</th>
            <th>Contribution Type</th>
            <th>Remark</th>
            <th>Credited By</th>
            <th>Credited On</th>
            </tr>
        </thead>

        <tbody>

            @foreach ($contributions as $contribution)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $contribution->user->fullname }} </td>
                    <td>{{ $contribution->amount }} </td>
                    <td>{{ $contribution->contribution_type->name }} </td>
                    <td>{{ $contribution->remark }} </td>
                    <td>{{ $contribution->creditor->fullname }} </td>
                    <td>{{ $contribution->created_at }}</td>
                </tr>
            @endforeach
            
        </tbody>
</table>

</body>
</html>

resources/views/pdf/employee_contributions_formatted.blade.php
<!DOCTYPE html>
<html>
<head>
        
    <title></title>
    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body{
            color: #1f2877;
            font-family: "Sans-serif";
            font-size: 12px;
        }
        div{
            margin-top: 10px;
        }

        hr{
            height: 1px;
            border-top: 0px;
            border-left: 0px;
            border-right: 0px;
        }

        .pull-right{
            float: right;
        }

        .table-header{
            width: 97%;
            overflow: auto;
            font-weight: bold;
        }

        .table-header div{
            width: 33%;
            float: left;
            margin: 0%;
            padding: 5px;
            border-bottom: 1.5px solid #1f2877;
        }

        .table-body{
            width: 97%;
            overflow: auto;
        }

        .table-body div{
            width: 33%;
            float: left;
            margin: 0%;
            padding: 5px;
            /* border-bottom: 1px solid #1f2877; */
        }

        .text-center{
            text-align: center;
        }
        
        .text-right{
            text-align: right;
        }

        .text-black{
            color: black !important;
        }

        .border-black{
            border-bottom: 1px solid black;
        }

        .bg-black{
            background: black;
        }

        .b{
            font-weight: bold;
        }

    </style>

</head>
<body>

    {{--  Company Info Header  --}}
    <div style="text-align:center;">
        <h1>COCOA HEALTH AND EXTENSION DIVISION</h1>
        <h2>COCOA MUTUAL REPORT</h2>
        <h4> {{ strtoupper($user->region->name) }} </h4>
    </div>
    <br/>
    <div>
        <b>NAME: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ $user->fullname }}</b>
    </div>
    <div>
        <b>STAFF ID: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ $user->username }}</b>
        <b class="pull-right">TERMINATED/RETIREDSTAFF?: &nbsp;&nbsp;&nbsp;
            @if( !empty($user->deleted_at) )
                YES
            @else
                NO
            @endif
        </b>
    </div>

    <hr/>

    @php
        $current_balance = 0;    
        $total_contribution = 0;    
        $total_with_interest = 0;  
        $total_interest = 0;    
    @endphp

        @if( empty($roll_over) )
            OPENING BALANCE <b class="pull-right">0.00</b>
        @else
            ({{ $roll_over->formatted_start_date }} - {{ $roll_over->formatted_end_date }}) OPENING BALANCE <b class="pull-right">{{ $roll_over->formatted_old_balance }}</b>

            @php
                $current_balance = $roll_over->balance - $roll_over->amount_withdrawn;   
            @endphp
        @endif
    <hr/>

        
    <div class="table-header">
        <div class="table-header-div">MONTH</div>
        <div class="text-center table-header-div">CONTIBUTION</div>
        <div class="text-center table-header-div ">BALANCE</div>
    </div>
    


    

    @foreach ($contributions as $contribution)
        
        <br/>
        <br/>
        <div class="table-body">
            <div class=" border-black">{{ $contribution->formatted_date }}</div>
            <div class="text-center text-black  border-black">
                @php
                    $total_contribution += $contribution->amount;
                @endphp
                {{ $contribution->formatted_amount }}
            </div>
            <div class="text-center text-black  border-black">
                @php
                    $current_balance = $current_balance + $contribution->amount;   
                @endphp
                {{ number_format( $current_balance, 2 ) }}
            </div>
        </div>

    @endforeach

        {{--  Total Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">TOTAL</div>
            <div class="text-center text-black  border-black">
                {{ number_format( $total_contribution, 2 ) }}
            </div>
            <div class="text-center text-black  border-black">
                {{ number_format( $current_balance, 2 ) }}
            </div>
        </div>

        {{--  Interest Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">{{ date('Y')}} INTEREST
                @if( empty( $interest ) )
                    0 (%)
                @else
                    {{ $interest->amount }}
                    (%)

                    @php
                        $total_interest = ( $interest->amount / 100 ) * $current_balance;
                        $total_with_interest = $current_balance + $total_interest;
                    @endphp

                @endif                
            </div>
            <div class="text-center text-black  border-black">
                &nbsp;
            </div>
            <div class="text-center text-black  border-black">
                {{ number_format( $total_interest, 2 ) }}
            </div>
        </div>

        {{--  Total with Interest Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">TOTAL WITH INTEREST</div>
            <div class="text-center text-black  border-black">
                &nbsp;
            </div>
            <div class="text-center text-black  border-black">
                {{ number_format( $total_with_interest, 2 ) }}
            </div>
        </div>

        {{--  Year Withdraw Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">{{ date('Y') }} WITHDRAWAL</div>
            <div class="text-center text-black  border-black">
                &nbsp;
            </div>
            <div class="text-center text-black  border-black">
                {{ number_format( $withdrawal, 2 ) }}
            </div>
        </div>

        {{--  Balance  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black b">BALANCE AS AT</div>
            <div class="text-center text-black  border-black">
                &nbsp;
            </div>
            <div class="text-center text-black  border-black b">
                @php
                    $total_current_balance = $total_with_interest - $withdrawal;
                @endphp
                {{ number_format( $total_current_balance, 2 ) }}
            </div>
        </div>
    
    

</body>
</html>

resources/views/pdf/my_contributions.blade.php
<!DOCTYPE html>
<html>
<head>
        
    <title></title>
    <!-- Bootstrap -->
    <link href="../vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        body{
            color: #1f2877;
            font-family: "Sans-serif";
            font-size: 12px;
        }
        div{
            margin-top: 10px;
        }

        hr{
            height: 1px;
            border-top: 0px;
            border-left: 0px;
            border-right: 0px;
        }

        .pull-right{
            float: right;
        }

        .table-header{
            width: 97%;
            overflow: auto;
            font-weight: bold;
        }

        .table-header div{
            width: 33%;
            float: left;
            margin: 0%;
            padding: 5px;
            border-bottom: 1.5px solid #1f2877;
        }

        .table-body{
            width: 97%;
            overflow: auto;
        }

        .table-body div{
            width: 33%;
            float: left;
            margin: 0%;
            padding: 5px;
            /* border-bottom: 1px solid #1f2877; */
        }

        .text-center{
            text-align: center;
        }
        
        .text-right{
            text-align: right;
        }

        .text-black{
            color: black !important;
        }

        .border-black{
            border-bottom: 1px solid black;
        }

        .bg-black{
            background: black;
        }

        .b{
            font-weight: bold;
        }

    </style>

</head>
<body>

    {{--  Company Info Header  --}}
    <div style="text-align:center;">
        <h1>COCOA HEALTH AND EXTENSION DIVISION</h1>
        <h2>COCOA MUTUAL REPORT</h2>
        <h4> {{ strtoupper(Auth::user()->region->name) }} </h4>
    </div>
    <br/>
    <div>
        <b>NAME: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ Auth::user()->fullname }}</b>
    </div>
    <div>
        <b>STAFF ID: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ Auth::user()->username }}</b>
        <b class="pull-right">TERMINATED/RETIREDSTAFF?: &nbsp;&nbsp;&nbsp;
            @if( !empty($user->deleted_at) )
                YES
            @else
                NO
            @endif
        </b>
    </div>

    <hr/>

    @php
        $current_balance = 0;    
        $total_contribution = 0;    
        $total_with_interest = 0;  
        $total_interest = 0;    
    @endphp

        @if( empty($roll_over) )
            OPENING BALANCE <b class="pull-right">0.00</b>
        @else
            ({{ $roll_over->formatted_start_date }} - {{ $roll_over->formatted_end_date }}) OPENING BALANCE <b class="pull-right">{{ $roll_over->formatted_old_balance }}</b>

            @php
                $current_balance = $roll_over->balance - $roll_over->amount_withdrawn;   
            @endphp
        @endif
    <hr/>

        
    <div class="table-header">
        <div class="table-header-div">MONTH</div>
        <div class="text-center table-header-div">CONTIBUTION</div>
        <div class="text-center table-header-div ">BALANCE</div>
    </div>
    


    

    @foreach ($contributions as $contribution)
        
        <br/>
        <br/>
        <div class="table-body">
            <div class=" border-black">{{ $contribution->formatted_date }}</div>
            <div class="text-center text-black  border-black">
                @php
                    $total_contribution += $contribution->amount;
                @endphp
                {{ $contribution->formatted_amount }}
            </div>
            <div class="text-center text-black  border-black">
                @php
                    $current_balance = $current_balance + $contribution->amount;   
                @endphp
                {{ number_format( $current_balance, 2 ) }}
            </div>
        </div>

    @endforeach

        {{--  Total Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">TOTAL</div>
            <div class="text-center text-black  border-black">
                {{ number_format( $total_contribution, 2 ) }}
            </div>
            <div class="text-center text-black  border-black">
                {{ number_format( $current_balance, 2 ) }}
            </div>
        </div>

        {{--  Interest Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">{{ date('Y')}} INTEREST
                @if( empty( $interest ) )
                    0 (%)
                @else

                    {{ $interest->amount }}
                    (%)

                    @php
                        $total_interest = ( $interest->amount / 100 ) * $current_balance;
                        $total_with_interest = $current_balance + $total_interest;
                    @endphp

                @endif                
            </div>
            <div class="text-center text-black  border-black">
                &nbsp;
            </div>
            <div class="text-center text-black  border-black">
                {{ number_format( $total_interest, 2 ) }}
            </div>
        </div>

        {{--  Total with Interest Section  --}}
        <br/>
        <br/>
        <div class="table-body">
            <div class="text-black border-black">TOTAL WITH INTEREST</div>
            <div class="text-center text-black  border-black">
                &nbsp;
            </div>
            <div class="text-center text-black  border-black">

                @if( $total_with_interest <= 0 )
                    {{ number_format( $current_balance, 2 ) }}
                @else
                    {{ number_format( $total_with_interest, 2 ) }}
                @endif

            </div>
        </div>

</body>
</html>

resources/views/pdf/my_withdrawals.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
    
    <style>

        .p2{
            padding: 5px;
        }

        table {
            border-collapse: collapse;
        }

        table, th, td {
            border: 1px solid black;
        }

        table {
            width: 100%;
        }

        th {
            height: 20px;
        }

    </style>

</head>
<body>

    <p style="text-align:center;padding:10px;"><h3> Withdrawals Report </h3></p>
<table>
        <thead>
            <tr>
                <th class="p2">ID</th>
                <th class="p2">Amount</th>
                <th class="p2">Remark</th>
                <th class="p2">Status</th>
                <th class="p2">Approved/Disapproved By</th>
                <th class="p2">Credited On</th>
            </tr>
        </thead>

        <tbody>

                @foreach ($withdrawals as $withdrawal)
                <tr>
                    <td class="p2">{{ $loop->iteration }}</td>
                    <td class="p2">{{ $withdrawal->amount }} </td>
                    <td class="p2">{{ $withdrawal->remark }} </td>
                    <td class="p2">
                        @if(!empty($withdrawal->deleted_at))
                            <i class="btn btn-danger btn-sm">Disapproved</i>
                        @elseif(!empty($withdrawal->approved_date))
                            <i class="btn btn-success btn-sm">Approved</i>
                        @else
                            <i class="btn btn-warning btn-sm">Pending</i>
                        @endif
                    </td>
                    <td class="p2">
                        @if( !empty($withdrawal->approver) )
                            {{ $withdrawal->approver->fullname }} 
                        @endif
                    </td>
                    <td class="p2">{{ $withdrawal->created_at }}</td>
                </tr>
            @endforeach
            
        </tbody>
</table>

</body>
</html>

resources/views/pdf/withdrawals.blade.php
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <style>

            .p2{
                padding: 5px;
            }
    
            table {
                border-collapse: collapse;
            }
    
            table, th, td {
                border: 1px solid black;
            }
    
            table {
                width: 100%;
            }
    
            th {
                height: 20px;
            }
    
        </style>
</head>
<body>

    <p style="text-align:center;padding:10px;"><h3> Withdrawals Report </h3></p>
<table>
        <thead>
            <tr>
                <th class="p2">ID</th>
                <th class="p2">Fullname</th>
                <th class="p2">Amount</th>
                <th class="p2">Remark</th>
                <th class="p2">Credited On</th>
                <th class="p2">Status</th>
            </tr>
        </thead>

        <tbody>

                @foreach ($withdrawals as $withdrawal)
                <tr>
                    <td class="p2">{{ $loop->iteration }}</td>
                    <td class="p2">{{ $withdrawal->user->fullname }} </td>
                    <td class="p2">{{ $withdrawal->amount }} </td>
                    <td class="p2">{{ $withdrawal->remark }} </td>
                    <td class="p2">{{ $withdrawal->created_at }}</td>
                    <td class="p2">
                        @if(!empty($withdrawal->deleted_at))
                            <i class="btn btn-danger btn-sm">Disapproved</i>
                        @elseif(!empty($withdrawal->approved_date))
                            <i class="btn btn-success btn-sm">Approved</i>
                        @else
                            <i class="btn btn-warning btn-sm">Pending</i>
                        @endif
                    </td>
                </tr>
            @endforeach
            
        </tbody>
</table>

</body>
</html>